### ISSUE TITLE
Fix over-scrolling when no kit selected

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#300] opened 2018-05-22 18:48 UTC
![screenshot 2018-05-22 20 41 27](https://user-images.githubusercontent.com/74249/40383555-74d72b1c-5e01-11e8-951c-1558898987be.png)

Check this threat.

https://stackoverflow.com/questions/12046315/prevent-overscrolling-of-web-page

**Comment by viktorsmari** [comment] 2018-05-31 09:50
This was fixed with this commit:
https://github.com/fablabbcn/smartcitizen-web/commit/f8956966b6cfdb3224df094bde7f9bd54512f99f
**But** this broke something else on the page. So the issue is back :tada:

**Closed** 2019-07-23 15:26 UTC
Labels: bug
